"""ISO 27001:2022 Annex A — 4 themes, 93 controls."""

from security_agents.core.grc_models import Control, Framework
from security_agents.core.grc_frameworks import _register

_CONTROLS = [
    # =========================================================================
    # A.5 — Organizational Controls (37 controls)
    # =========================================================================
    Control(id="A.5.1", framework_id="iso_27001_2022", parent_id="A.5", title="Policies for information security",
            description="Information security policy and topic-specific policies shall be defined, approved, published, communicated, and reviewed."),
    Control(id="A.5.2", framework_id="iso_27001_2022", parent_id="A.5", title="Information security roles and responsibilities",
            description="Information security roles and responsibilities shall be defined and allocated."),
    Control(id="A.5.3", framework_id="iso_27001_2022", parent_id="A.5", title="Segregation of duties",
            description="Conflicting duties and conflicting areas of responsibility shall be segregated."),
    Control(id="A.5.4", framework_id="iso_27001_2022", parent_id="A.5", title="Management responsibilities",
            description="Management shall require all personnel to apply information security in accordance with policies."),
    Control(id="A.5.5", framework_id="iso_27001_2022", parent_id="A.5", title="Contact with authorities",
            description="The organization shall establish and maintain contact with relevant authorities."),
    Control(id="A.5.6", framework_id="iso_27001_2022", parent_id="A.5", title="Contact with special interest groups",
            description="The organization shall establish and maintain contact with special interest groups."),
    Control(id="A.5.7", framework_id="iso_27001_2022", parent_id="A.5", title="Threat intelligence",
            description="Information relating to information security threats shall be collected and analysed."),
    Control(id="A.5.8", framework_id="iso_27001_2022", parent_id="A.5", title="Information security in project management",
            description="Information security shall be integrated into project management."),
    Control(id="A.5.9", framework_id="iso_27001_2022", parent_id="A.5", title="Inventory of information and other associated assets",
            description="An inventory of information and other associated assets shall be developed and maintained."),
    Control(id="A.5.10", framework_id="iso_27001_2022", parent_id="A.5", title="Acceptable use of information and other associated assets",
            description="Rules for the acceptable use and procedures for handling information shall be identified and documented."),
    Control(id="A.5.11", framework_id="iso_27001_2022", parent_id="A.5", title="Return of assets",
            description="Personnel and other interested parties shall return all organizational assets on change or termination."),
    Control(id="A.5.12", framework_id="iso_27001_2022", parent_id="A.5", title="Classification of information",
            description="Information shall be classified according to the information security needs of the organization."),
    Control(id="A.5.13", framework_id="iso_27001_2022", parent_id="A.5", title="Labelling of information",
            description="An appropriate set of procedures for information labelling shall be developed and implemented."),
    Control(id="A.5.14", framework_id="iso_27001_2022", parent_id="A.5", title="Information transfer",
            description="Information transfer rules, procedures, or agreements shall be in place for all types of transfer."),
    Control(id="A.5.15", framework_id="iso_27001_2022", parent_id="A.5", title="Access control",
            description="Rules to control physical and logical access to information shall be established and implemented."),
    Control(id="A.5.16", framework_id="iso_27001_2022", parent_id="A.5", title="Identity management",
            description="The full life cycle of identities shall be managed."),
    Control(id="A.5.17", framework_id="iso_27001_2022", parent_id="A.5", title="Authentication information",
            description="Allocation and management of authentication information shall be controlled."),
    Control(id="A.5.18", framework_id="iso_27001_2022", parent_id="A.5", title="Access rights",
            description="Access rights to information shall be provisioned, reviewed, modified and removed."),
    Control(id="A.5.19", framework_id="iso_27001_2022", parent_id="A.5", title="Information security in supplier relationships",
            description="Processes and procedures shall be defined and implemented to manage information security risks."),
    Control(id="A.5.20", framework_id="iso_27001_2022", parent_id="A.5", title="Addressing information security within supplier agreements",
            description="Relevant information security requirements shall be established and agreed with each supplier."),
    Control(id="A.5.21", framework_id="iso_27001_2022", parent_id="A.5", title="Managing information security in the ICT supply chain",
            description="Processes and procedures shall be defined and implemented to manage ICT supply chain risks."),
    Control(id="A.5.22", framework_id="iso_27001_2022", parent_id="A.5", title="Monitoring, review and change management of supplier services",
            description="The organization shall regularly monitor, review, evaluate and manage change in supplier practices."),
    Control(id="A.5.23", framework_id="iso_27001_2022", parent_id="A.5", title="Information security for use of cloud services",
            description="Processes for acquisition, use, management and exit from cloud services shall be established."),
    Control(id="A.5.24", framework_id="iso_27001_2022", parent_id="A.5", title="Information security incident management planning and preparation",
            description="The organization shall plan and prepare for managing information security incidents."),
    Control(id="A.5.25", framework_id="iso_27001_2022", parent_id="A.5", title="Assessment and decision on information security events",
            description="The organization shall assess information security events and decide if they are incidents."),
    Control(id="A.5.26", framework_id="iso_27001_2022", parent_id="A.5", title="Response to information security incidents",
            description="Information security incidents shall be responded to in accordance with documented procedures."),
    Control(id="A.5.27", framework_id="iso_27001_2022", parent_id="A.5", title="Learning from information security incidents",
            description="Knowledge gained from information security incidents shall be used to strengthen controls."),
    Control(id="A.5.28", framework_id="iso_27001_2022", parent_id="A.5", title="Collection of evidence",
            description="The organization shall establish and implement procedures for identification and collection of evidence."),
    Control(id="A.5.29", framework_id="iso_27001_2022", parent_id="A.5", title="Information security during disruption",
            description="The organization shall plan how to maintain information security during disruption."),
    Control(id="A.5.30", framework_id="iso_27001_2022", parent_id="A.5", title="ICT readiness for business continuity",
            description="ICT readiness shall be planned, implemented, maintained and tested."),
    Control(id="A.5.31", framework_id="iso_27001_2022", parent_id="A.5", title="Legal, statutory, regulatory and contractual requirements",
            description="Legal, statutory, regulatory and contractual requirements shall be identified and documented."),
    Control(id="A.5.32", framework_id="iso_27001_2022", parent_id="A.5", title="Intellectual property rights",
            description="The organization shall implement appropriate procedures to protect intellectual property rights."),
    Control(id="A.5.33", framework_id="iso_27001_2022", parent_id="A.5", title="Protection of records",
            description="Records shall be protected from loss, destruction, falsification, unauthorized access."),
    Control(id="A.5.34", framework_id="iso_27001_2022", parent_id="A.5", title="Privacy and protection of PII",
            description="The organization shall identify and meet requirements regarding privacy and PII protection."),
    Control(id="A.5.35", framework_id="iso_27001_2022", parent_id="A.5", title="Independent review of information security",
            description="The organization's approach to managing information security shall be independently reviewed."),
    Control(id="A.5.36", framework_id="iso_27001_2022", parent_id="A.5", title="Compliance with policies, rules and standards for information security",
            description="Compliance with the organization's information security policy shall be regularly reviewed."),
    Control(id="A.5.37", framework_id="iso_27001_2022", parent_id="A.5", title="Documented operating procedures",
            description="Operating procedures for information processing facilities shall be documented."),

    # =========================================================================
    # A.6 — People Controls (8 controls)
    # =========================================================================
    Control(id="A.6.1", framework_id="iso_27001_2022", parent_id="A.6", title="Screening",
            description="Background verification checks on all candidates for employment shall be carried out."),
    Control(id="A.6.2", framework_id="iso_27001_2022", parent_id="A.6", title="Terms and conditions of employment",
            description="Employment contractual agreements shall state personnel's information security responsibilities."),
    Control(id="A.6.3", framework_id="iso_27001_2022", parent_id="A.6", title="Information security awareness, education and training",
            description="Personnel shall receive appropriate information security awareness, education and training."),
    Control(id="A.6.4", framework_id="iso_27001_2022", parent_id="A.6", title="Disciplinary process",
            description="A disciplinary process shall be formalized and communicated."),
    Control(id="A.6.5", framework_id="iso_27001_2022", parent_id="A.6", title="Responsibilities after termination or change of employment",
            description="Information security responsibilities after termination or change of employment shall be defined."),
    Control(id="A.6.6", framework_id="iso_27001_2022", parent_id="A.6", title="Confidentiality or non-disclosure agreements",
            description="Confidentiality or non-disclosure agreements reflecting the organization's needs shall be signed."),
    Control(id="A.6.7", framework_id="iso_27001_2022", parent_id="A.6", title="Remote working",
            description="Security measures shall be implemented when personnel are working remotely."),
    Control(id="A.6.8", framework_id="iso_27001_2022", parent_id="A.6", title="Information security event reporting",
            description="Personnel shall be provided a mechanism to report observed or suspected information security events."),

    # =========================================================================
    # A.7 — Physical Controls (14 controls)
    # =========================================================================
    Control(id="A.7.1", framework_id="iso_27001_2022", parent_id="A.7", title="Physical security perimeters",
            description="Security perimeters shall be defined and used to protect areas containing information."),
    Control(id="A.7.2", framework_id="iso_27001_2022", parent_id="A.7", title="Physical entry",
            description="Secure areas shall be protected by appropriate entry controls."),
    Control(id="A.7.3", framework_id="iso_27001_2022", parent_id="A.7", title="Securing offices, rooms and facilities",
            description="Physical security for offices, rooms and facilities shall be designed and implemented."),
    Control(id="A.7.4", framework_id="iso_27001_2022", parent_id="A.7", title="Physical security monitoring",
            description="Premises shall be continuously monitored for unauthorized physical access."),
    Control(id="A.7.5", framework_id="iso_27001_2022", parent_id="A.7", title="Protecting against physical and environmental threats",
            description="Protection against physical and environmental threats shall be designed and implemented."),
    Control(id="A.7.6", framework_id="iso_27001_2022", parent_id="A.7", title="Working in secure areas",
            description="Security measures for working in secure areas shall be designed and implemented."),
    Control(id="A.7.7", framework_id="iso_27001_2022", parent_id="A.7", title="Clear desk and clear screen",
            description="Clear desk rules for papers and clear screen rules for information processing facilities."),
    Control(id="A.7.8", framework_id="iso_27001_2022", parent_id="A.7", title="Equipment siting and protection",
            description="Equipment shall be sited securely and protected."),
    Control(id="A.7.9", framework_id="iso_27001_2022", parent_id="A.7", title="Security of assets off-premises",
            description="Off-site assets shall be protected."),
    Control(id="A.7.10", framework_id="iso_27001_2022", parent_id="A.7", title="Storage media",
            description="Storage media shall be managed through their life cycle."),
    Control(id="A.7.11", framework_id="iso_27001_2022", parent_id="A.7", title="Supporting utilities",
            description="Information processing facilities shall be protected from power failures."),
    Control(id="A.7.12", framework_id="iso_27001_2022", parent_id="A.7", title="Cabling security",
            description="Cables carrying power, data or supporting information services shall be protected."),
    Control(id="A.7.13", framework_id="iso_27001_2022", parent_id="A.7", title="Equipment maintenance",
            description="Equipment shall be maintained correctly to ensure availability and integrity of information."),
    Control(id="A.7.14", framework_id="iso_27001_2022", parent_id="A.7", title="Secure disposal or re-use of equipment",
            description="Items of equipment containing storage media shall be verified to ensure sensitive data is removed."),

    # =========================================================================
    # A.8 — Technological Controls (34 controls)
    # =========================================================================
    Control(id="A.8.1", framework_id="iso_27001_2022", parent_id="A.8", title="User endpoint devices",
            description="Information stored on, processed by or accessible via user endpoint devices shall be protected."),
    Control(id="A.8.2", framework_id="iso_27001_2022", parent_id="A.8", title="Privileged access rights",
            description="The allocation and use of privileged access rights shall be restricted and managed."),
    Control(id="A.8.3", framework_id="iso_27001_2022", parent_id="A.8", title="Information access restriction",
            description="Access to information shall be restricted in accordance with the access control topic-specific policy."),
    Control(id="A.8.4", framework_id="iso_27001_2022", parent_id="A.8", title="Access to source code",
            description="Read and write access to source code, development tools and software libraries shall be managed."),
    Control(id="A.8.5", framework_id="iso_27001_2022", parent_id="A.8", title="Secure authentication",
            description="Secure authentication technologies and procedures shall be established and implemented."),
    Control(id="A.8.6", framework_id="iso_27001_2022", parent_id="A.8", title="Capacity management",
            description="The use of resources shall be monitored and adjusted in line with capacity requirements."),
    Control(id="A.8.7", framework_id="iso_27001_2022", parent_id="A.8", title="Protection against malware",
            description="Protection against malware shall be implemented and supported by user awareness."),
    Control(id="A.8.8", framework_id="iso_27001_2022", parent_id="A.8", title="Management of technical vulnerabilities",
            description="Information about technical vulnerabilities shall be obtained and appropriate measures taken."),
    Control(id="A.8.9", framework_id="iso_27001_2022", parent_id="A.8", title="Configuration management",
            description="Configurations, including security configurations, of hardware, software, services and networks shall be managed."),
    Control(id="A.8.10", framework_id="iso_27001_2022", parent_id="A.8", title="Information deletion",
            description="Information stored in information systems, devices or in any other storage media shall be deleted when no longer required."),
    Control(id="A.8.11", framework_id="iso_27001_2022", parent_id="A.8", title="Data masking",
            description="Data masking shall be used in accordance with the organization's topic-specific policy."),
    Control(id="A.8.12", framework_id="iso_27001_2022", parent_id="A.8", title="Data leakage prevention",
            description="Data leakage prevention measures shall be applied to systems, networks and devices."),
    Control(id="A.8.13", framework_id="iso_27001_2022", parent_id="A.8", title="Information backup",
            description="Backup copies of information, software and systems shall be maintained and regularly tested."),
    Control(id="A.8.14", framework_id="iso_27001_2022", parent_id="A.8", title="Redundancy of information processing facilities",
            description="Information processing facilities shall be implemented with redundancy to meet availability requirements."),
    Control(id="A.8.15", framework_id="iso_27001_2022", parent_id="A.8", title="Logging",
            description="Logs that record activities, exceptions, faults and other relevant events shall be produced and protected."),
    Control(id="A.8.16", framework_id="iso_27001_2022", parent_id="A.8", title="Monitoring activities",
            description="Networks, systems and applications shall be monitored for anomalous behaviour."),
    Control(id="A.8.17", framework_id="iso_27001_2022", parent_id="A.8", title="Clock synchronization",
            description="The clocks of information processing systems shall be synchronized to approved time sources."),
    Control(id="A.8.18", framework_id="iso_27001_2022", parent_id="A.8", title="Use of privileged utility programs",
            description="The use of utility programs that might be capable of overriding controls shall be restricted."),
    Control(id="A.8.19", framework_id="iso_27001_2022", parent_id="A.8", title="Installation of software on operational systems",
            description="Procedures and measures shall be implemented to securely manage software installation."),
    Control(id="A.8.20", framework_id="iso_27001_2022", parent_id="A.8", title="Networks security",
            description="Networks and network devices shall be secured, managed and controlled."),
    Control(id="A.8.21", framework_id="iso_27001_2022", parent_id="A.8", title="Security of network services",
            description="Security mechanisms, service levels and service requirements of network services shall be managed."),
    Control(id="A.8.22", framework_id="iso_27001_2022", parent_id="A.8", title="Segregation of networks",
            description="Groups of information services, users and information systems shall be segregated."),
    Control(id="A.8.23", framework_id="iso_27001_2022", parent_id="A.8", title="Web filtering",
            description="Access to external websites shall be managed to reduce exposure to malicious content."),
    Control(id="A.8.24", framework_id="iso_27001_2022", parent_id="A.8", title="Use of cryptography",
            description="Rules for the effective use of cryptography shall be defined and implemented."),
    Control(id="A.8.25", framework_id="iso_27001_2022", parent_id="A.8", title="Secure development life cycle",
            description="Rules for the secure development of software and systems shall be established and applied."),
    Control(id="A.8.26", framework_id="iso_27001_2022", parent_id="A.8", title="Application security requirements",
            description="Information security requirements shall be identified and specified when developing or acquiring applications."),
    Control(id="A.8.27", framework_id="iso_27001_2022", parent_id="A.8", title="Secure system architecture and engineering principles",
            description="Principles for engineering secure systems shall be established and applied."),
    Control(id="A.8.28", framework_id="iso_27001_2022", parent_id="A.8", title="Secure coding",
            description="Secure coding principles shall be applied to software development."),
    Control(id="A.8.29", framework_id="iso_27001_2022", parent_id="A.8", title="Security testing in development and acceptance",
            description="Security testing processes shall be defined and implemented in the development life cycle."),
    Control(id="A.8.30", framework_id="iso_27001_2022", parent_id="A.8", title="Outsourced development",
            description="The organization shall direct, monitor and review outsourced system development activities."),
    Control(id="A.8.31", framework_id="iso_27001_2022", parent_id="A.8", title="Separation of development, test and production environments",
            description="Development, testing and production environments shall be separated and secured."),
    Control(id="A.8.32", framework_id="iso_27001_2022", parent_id="A.8", title="Change management",
            description="Changes to information processing facilities and information systems shall be subject to change management."),
    Control(id="A.8.33", framework_id="iso_27001_2022", parent_id="A.8", title="Test information",
            description="Test information shall be appropriately selected, protected and managed."),
    Control(id="A.8.34", framework_id="iso_27001_2022", parent_id="A.8", title="Protection of information systems during audit testing",
            description="Audit tests and other assurance activities involving assessment of operational systems shall be planned."),
]

ISO_27001_2022 = Framework(
    id="iso_27001_2022",
    name="ISO/IEC 27001:2022",
    version="2022",
    structure_type="hierarchical",
    controls=_CONTROLS,
)

_register(ISO_27001_2022)
