"""NIST Cybersecurity Framework 2.0 — 6 functions, 22 categories, 106 subcategories."""

from security_agents.core.grc_models import Control, Framework
from security_agents.core.grc_frameworks import _register

_CONTROLS = [
    # =========================================================================
    # GOVERN (GV) — new in CSF 2.0
    # =========================================================================
    Control(id="GV.OC-01", framework_id="nist_csf_2_0", parent_id="GV.OC", title="Organizational Context",
            description="The organizational mission is understood and informs cybersecurity risk management."),
    Control(id="GV.OC-02", framework_id="nist_csf_2_0", parent_id="GV.OC", title="Internal Stakeholders",
            description="Internal stakeholders understand and support cybersecurity risk management."),
    Control(id="GV.OC-03", framework_id="nist_csf_2_0", parent_id="GV.OC", title="Legal and Regulatory",
            description="Legal, regulatory, and contractual requirements are understood and managed."),
    Control(id="GV.OC-04", framework_id="nist_csf_2_0", parent_id="GV.OC", title="Critical Objectives",
            description="Critical objectives, capabilities, and services are understood."),
    Control(id="GV.OC-05", framework_id="nist_csf_2_0", parent_id="GV.OC", title="Outcomes and Dependencies",
            description="Outcomes, capabilities, and services that depend on external parties are understood."),
    Control(id="GV.RM-01", framework_id="nist_csf_2_0", parent_id="GV.RM", title="Risk Management Objectives",
            description="Risk management objectives are established and agreed upon."),
    Control(id="GV.RM-02", framework_id="nist_csf_2_0", parent_id="GV.RM", title="Risk Appetite",
            description="Risk appetite and tolerance statements are established and communicated."),
    Control(id="GV.RM-03", framework_id="nist_csf_2_0", parent_id="GV.RM", title="Risk Management Activities",
            description="Cybersecurity risk management activities and outcomes are included in enterprise risk management."),
    Control(id="GV.RM-04", framework_id="nist_csf_2_0", parent_id="GV.RM", title="Strategic Direction",
            description="Strategic direction that describes appropriate risk response options is established."),
    Control(id="GV.RR-01", framework_id="nist_csf_2_0", parent_id="GV.RR", title="Roles and Responsibilities",
            description="Organizational leadership establishes cybersecurity roles, responsibilities, and authorities."),
    Control(id="GV.RR-02", framework_id="nist_csf_2_0", parent_id="GV.RR", title="Enforcement",
            description="Roles, responsibilities, and authorities are enforced and reviewed."),
    Control(id="GV.RR-03", framework_id="nist_csf_2_0", parent_id="GV.RR", title="Adequate Resources",
            description="Adequate resources are allocated commensurate with cybersecurity risk strategy."),
    Control(id="GV.RR-04", framework_id="nist_csf_2_0", parent_id="GV.RR", title="Cybersecurity in HR",
            description="Cybersecurity is included in human resources practices."),
    Control(id="GV.PO-01", framework_id="nist_csf_2_0", parent_id="GV.PO", title="Policy Established",
            description="A policy for managing cybersecurity risks is established based on context and strategy."),
    Control(id="GV.PO-02", framework_id="nist_csf_2_0", parent_id="GV.PO", title="Policy Reviewed",
            description="Policy is reviewed, updated, communicated, and enforced."),
    Control(id="GV.SC-01", framework_id="nist_csf_2_0", parent_id="GV.SC", title="Supply Chain Program",
            description="A cybersecurity supply chain risk management program is established."),
    Control(id="GV.SC-02", framework_id="nist_csf_2_0", parent_id="GV.SC", title="Supplier Requirements",
            description="Cybersecurity roles and responsibilities for suppliers are established."),
    Control(id="GV.SC-03", framework_id="nist_csf_2_0", parent_id="GV.SC", title="Supply Chain Integration",
            description="Supply chain risk management is integrated into cybersecurity risk management."),
    Control(id="GV.SC-04", framework_id="nist_csf_2_0", parent_id="GV.SC", title="Supplier Assessment",
            description="Suppliers are assessed before and during relationships."),
    Control(id="GV.SC-05", framework_id="nist_csf_2_0", parent_id="GV.SC", title="Supply Chain Planning",
            description="Planning and due diligence are conducted to reduce risks before entering supply chain relationships."),

    # =========================================================================
    # IDENTIFY (ID)
    # =========================================================================
    Control(id="ID.AM-01", framework_id="nist_csf_2_0", parent_id="ID.AM", title="Hardware Inventory",
            description="Inventories of hardware managed by the organization are maintained."),
    Control(id="ID.AM-02", framework_id="nist_csf_2_0", parent_id="ID.AM", title="Software Inventory",
            description="Inventories of software, services, and systems managed by the organization are maintained."),
    Control(id="ID.AM-03", framework_id="nist_csf_2_0", parent_id="ID.AM", title="Network Communication",
            description="Representations of authorized network communication and data flows are maintained."),
    Control(id="ID.AM-04", framework_id="nist_csf_2_0", parent_id="ID.AM", title="External Services",
            description="Inventories of services provided by suppliers are maintained."),
    Control(id="ID.AM-05", framework_id="nist_csf_2_0", parent_id="ID.AM", title="Asset Prioritization",
            description="Assets are prioritized based on classification, criticality, and value to the organization."),
    Control(id="ID.AM-07", framework_id="nist_csf_2_0", parent_id="ID.AM", title="Data Inventory",
            description="Inventories of data and corresponding metadata are maintained."),
    Control(id="ID.AM-08", framework_id="nist_csf_2_0", parent_id="ID.AM", title="System Dependencies",
            description="Systems, hardware, software, services, and data are managed throughout their life cycles."),
    Control(id="ID.RA-01", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Vulnerability Identification",
            description="Vulnerabilities in assets are identified, validated, and recorded."),
    Control(id="ID.RA-02", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Threat Intelligence",
            description="Cyber threat intelligence is received from information sharing forums and sources."),
    Control(id="ID.RA-03", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Threat Identification",
            description="Internal and external threats to the organization are identified and recorded."),
    Control(id="ID.RA-04", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Risk Determination",
            description="Potential impacts and likelihoods of threats exploiting vulnerabilities are identified."),
    Control(id="ID.RA-05", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Risk Response",
            description="Threats, vulnerabilities, likelihoods, and impacts are used to understand risk and inform response."),
    Control(id="ID.RA-06", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Risk Prioritization",
            description="Risk responses are chosen, prioritized, planned, tracked, and communicated."),
    Control(id="ID.RA-07", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Changes and Exceptions",
            description="Changes and exceptions are managed, assessed for risk impact, recorded, and tracked."),
    Control(id="ID.RA-08", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Vulnerability Response",
            description="Processes for receiving, analyzing, and responding to vulnerability disclosures are established."),
    Control(id="ID.RA-09", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Risk Assessment Integrity",
            description="The authenticity and integrity of hardware and software are assessed prior to acquisition."),
    Control(id="ID.RA-10", framework_id="nist_csf_2_0", parent_id="ID.RA", title="Supplier Risk",
            description="Critical suppliers are assessed prior to acquisition."),
    Control(id="ID.IM-01", framework_id="nist_csf_2_0", parent_id="ID.IM", title="Improvement from Evaluations",
            description="Improvements are identified from evaluations."),
    Control(id="ID.IM-02", framework_id="nist_csf_2_0", parent_id="ID.IM", title="Improvement from Tests",
            description="Improvements are identified from security tests and exercises."),
    Control(id="ID.IM-03", framework_id="nist_csf_2_0", parent_id="ID.IM", title="Improvement from Operations",
            description="Improvements are identified from execution of operational processes."),
    Control(id="ID.IM-04", framework_id="nist_csf_2_0", parent_id="ID.IM", title="Incident Lessons Learned",
            description="Incident response plans incorporate lessons learned."),

    # =========================================================================
    # PROTECT (PR)
    # =========================================================================
    Control(id="PR.AA-01", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Identity Management",
            description="Identities and credentials for authorized users, services, and hardware are managed."),
    Control(id="PR.AA-02", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Identity Proofing",
            description="Identities are proofed and bound to credentials based on context of interactions."),
    Control(id="PR.AA-03", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Authentication",
            description="Users, services, and hardware are authenticated."),
    Control(id="PR.AA-04", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Identity Assertions",
            description="Identity assertions are protected, conveyed, and verified."),
    Control(id="PR.AA-05", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Access Permissions",
            description="Access permissions, entitlements, and authorizations are managed."),
    Control(id="PR.AA-06", framework_id="nist_csf_2_0", parent_id="PR.AA", title="Physical Access",
            description="Physical access to assets is managed, monitored, and enforced."),
    Control(id="PR.AT-01", framework_id="nist_csf_2_0", parent_id="PR.AT", title="Awareness Training",
            description="Personnel are provided with awareness and training."),
    Control(id="PR.AT-02", framework_id="nist_csf_2_0", parent_id="PR.AT", title="Privileged User Training",
            description="Individuals in specialized roles are provided with awareness and training."),
    Control(id="PR.DS-01", framework_id="nist_csf_2_0", parent_id="PR.DS", title="Data-at-Rest Protection",
            description="The confidentiality, integrity, and availability of data-at-rest are protected."),
    Control(id="PR.DS-02", framework_id="nist_csf_2_0", parent_id="PR.DS", title="Data-in-Transit Protection",
            description="The confidentiality, integrity, and availability of data-in-transit are protected."),
    Control(id="PR.DS-10", framework_id="nist_csf_2_0", parent_id="PR.DS", title="Data-in-Use Protection",
            description="The confidentiality, integrity, and availability of data-in-use are protected."),
    Control(id="PR.DS-11", framework_id="nist_csf_2_0", parent_id="PR.DS", title="Backups",
            description="Backups of data are created, protected, maintained, and tested."),
    Control(id="PR.PS-01", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Configuration Management",
            description="Configuration management practices are established and applied."),
    Control(id="PR.PS-02", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Software Maintenance",
            description="Software is maintained, replaced, and removed commensurate with risk."),
    Control(id="PR.PS-03", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Hardware Maintenance",
            description="Hardware is maintained, replaced, and removed commensurate with risk."),
    Control(id="PR.PS-04", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Log Management",
            description="Log records are generated and made available for continuous monitoring."),
    Control(id="PR.PS-05", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Software Installation",
            description="Installation and execution of unauthorized software are prevented."),
    Control(id="PR.PS-06", framework_id="nist_csf_2_0", parent_id="PR.PS", title="Secure Development",
            description="Secure software development practices are integrated and applied."),
    Control(id="PR.IR-01", framework_id="nist_csf_2_0", parent_id="PR.IR", title="Network Resilience",
            description="Networks and environments are protected from unauthorized logical access."),
    Control(id="PR.IR-02", framework_id="nist_csf_2_0", parent_id="PR.IR", title="Technology Resilience",
            description="The organization's technology assets are protected from environmental threats."),
    Control(id="PR.IR-03", framework_id="nist_csf_2_0", parent_id="PR.IR", title="Resilience Mechanisms",
            description="Mechanisms are implemented to achieve resilience requirements in normal and adverse situations."),
    Control(id="PR.IR-04", framework_id="nist_csf_2_0", parent_id="PR.IR", title="Resource Adequacy",
            description="Adequate resource capacity to ensure availability is maintained."),

    # =========================================================================
    # DETECT (DE)
    # =========================================================================
    Control(id="DE.CM-01", framework_id="nist_csf_2_0", parent_id="DE.CM", title="Network Monitoring",
            description="Networks and network services are monitored to find potentially adverse events."),
    Control(id="DE.CM-02", framework_id="nist_csf_2_0", parent_id="DE.CM", title="Physical Monitoring",
            description="The physical environment is monitored to find potentially adverse events."),
    Control(id="DE.CM-03", framework_id="nist_csf_2_0", parent_id="DE.CM", title="Personnel Monitoring",
            description="Personnel activity and technology usage are monitored."),
    Control(id="DE.CM-06", framework_id="nist_csf_2_0", parent_id="DE.CM", title="External Provider Monitoring",
            description="External service provider activities and services are monitored."),
    Control(id="DE.CM-09", framework_id="nist_csf_2_0", parent_id="DE.CM", title="Computing Monitoring",
            description="Computing hardware and software, runtime environments, and their data are monitored."),
    Control(id="DE.AE-02", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Event Analysis",
            description="Potentially adverse events are analyzed to better understand associated activities."),
    Control(id="DE.AE-03", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Event Correlation",
            description="Information is correlated from multiple sources."),
    Control(id="DE.AE-04", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Impact Estimation",
            description="The estimated impact and scope of adverse events are understood."),
    Control(id="DE.AE-06", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Incident Declaration",
            description="Information on adverse events is provided to authorized staff and tools."),
    Control(id="DE.AE-07", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Threat Intelligence Integration",
            description="Cyber threat intelligence and other contextual information are integrated into the analysis."),
    Control(id="DE.AE-08", framework_id="nist_csf_2_0", parent_id="DE.AE", title="Anomaly Detection",
            description="Incidents are declared when adverse events meet the defined incident criteria."),

    # =========================================================================
    # RESPOND (RS)
    # =========================================================================
    Control(id="RS.MA-01", framework_id="nist_csf_2_0", parent_id="RS.MA", title="Incident Management",
            description="The incident response plan is executed in coordination with relevant third parties."),
    Control(id="RS.MA-02", framework_id="nist_csf_2_0", parent_id="RS.MA", title="Incident Triage",
            description="Incident reports are triaged and validated."),
    Control(id="RS.MA-03", framework_id="nist_csf_2_0", parent_id="RS.MA", title="Incident Categorization",
            description="Incidents are categorized and prioritized."),
    Control(id="RS.MA-04", framework_id="nist_csf_2_0", parent_id="RS.MA", title="Incident Escalation",
            description="Incidents are escalated or elevated as needed."),
    Control(id="RS.MA-05", framework_id="nist_csf_2_0", parent_id="RS.MA", title="Incident Criteria",
            description="The criteria for initiating incident recovery are applied."),
    Control(id="RS.AN-03", framework_id="nist_csf_2_0", parent_id="RS.AN", title="Root Cause Analysis",
            description="Analysis is performed to establish what has taken place and the root cause."),
    Control(id="RS.AN-06", framework_id="nist_csf_2_0", parent_id="RS.AN", title="Actions Taken",
            description="Actions performed during an investigation are recorded."),
    Control(id="RS.AN-07", framework_id="nist_csf_2_0", parent_id="RS.AN", title="Evidence Collection",
            description="Incident data and metadata are collected and their integrity preserved."),
    Control(id="RS.AN-08", framework_id="nist_csf_2_0", parent_id="RS.AN", title="Impact Assessment",
            description="An incident's magnitude is estimated and validated."),
    Control(id="RS.CO-02", framework_id="nist_csf_2_0", parent_id="RS.CO", title="Internal Communication",
            description="Internal and external stakeholders are notified of incidents."),
    Control(id="RS.CO-03", framework_id="nist_csf_2_0", parent_id="RS.CO", title="Information Sharing",
            description="Information is shared with designated internal and external stakeholders."),
    Control(id="RS.MI-01", framework_id="nist_csf_2_0", parent_id="RS.MI", title="Containment",
            description="Incidents are contained."),
    Control(id="RS.MI-02", framework_id="nist_csf_2_0", parent_id="RS.MI", title="Eradication",
            description="Incidents are eradicated."),

    # =========================================================================
    # RECOVER (RC)
    # =========================================================================
    Control(id="RC.RP-01", framework_id="nist_csf_2_0", parent_id="RC.RP", title="Recovery Execution",
            description="The recovery portion of the incident response plan is executed."),
    Control(id="RC.RP-02", framework_id="nist_csf_2_0", parent_id="RC.RP", title="Recovery Selection",
            description="Recovery actions are selected, scoped, prioritized, and performed."),
    Control(id="RC.RP-03", framework_id="nist_csf_2_0", parent_id="RC.RP", title="Backup Verification",
            description="The integrity of backups and other restoration assets is verified."),
    Control(id="RC.RP-04", framework_id="nist_csf_2_0", parent_id="RC.RP", title="System Restoration",
            description="Critical mission functions and cybersecurity risk management are considered."),
    Control(id="RC.RP-05", framework_id="nist_csf_2_0", parent_id="RC.RP", title="Recovery Verification",
            description="The integrity of restored assets is verified, systems and services are restored."),
    Control(id="RC.RP-06", framework_id="nist_csf_2_0", parent_id="RC.RP", title="End of Recovery",
            description="The end of incident recovery is declared based on criteria."),
    Control(id="RC.CO-03", framework_id="nist_csf_2_0", parent_id="RC.CO", title="Recovery Communication",
            description="Recovery activities and progress are communicated to internal and external stakeholders."),
    Control(id="RC.CO-04", framework_id="nist_csf_2_0", parent_id="RC.CO", title="Public Updates",
            description="Public updates on incident recovery are shared using approved methods and messaging."),
]

NIST_CSF_2_0 = Framework(
    id="nist_csf_2_0",
    name="NIST Cybersecurity Framework 2.0",
    version="2.0",
    structure_type="hierarchical",
    controls=_CONTROLS,
)

_register(NIST_CSF_2_0)
